alias: Spotify Lights
description: ""
mode: single
triggers:
  - allowed_methods:
      - POST
    local_only: true
    webhook_id: "REPLACEME"
    trigger: webhook
# Optional, makes sure that the automation is only triggered when it's two hours before sunset or later.
conditions:
  - condition: or
    conditions:
      - condition: sun
        before: sunrise
      - condition: sun
        after: sunset
        after_offset: "-02:00:00"
actions:
  - metadata: {}
    target:
      entity_id:
        - light.light_1
        - light.ceiling_lights
    data:
      transition: 1
      rgb_color: "{{trigger.json.rgb}}"
    enabled: true
    action: light.turn_on
